alias init-development='aws-profile -p upscan-labs terraform init --backend-config=../../backends/development.tfvars'
alias init-qa='aws-profile -p upscan-labs terraform init --backend-config=../../backends/qa.tfvars'
alias init-staging='aws-profile -p upscan-labs terraform init --backend-config=../../backends/staging.tfvars'
alias select-workspace-development='aws-profile -p upscan-labs terraform workspace select development'
alias select-workspace-qa='aws-profile -p upscan-labs terraform workspace select qa'
alias select-workspace-staging='aws-profile -p upscan-labs terraform workspace select staging'
alias save-labs-plan='aws-profile -p upscan-labs terraform plan -out tfplan.out'
alias save-live-plan='aws-profile -p upscan-live terraform plan -out tfplan.out'
alias show-labs-plan-json='aws-profile -p upscan-labs terraform show -json tfplan.out'
alias show-live-plan-json='aws-profile -p upscan-live terraform show -json tfplan.out'
