alias init-labs-development='aws-profile -p upscan-labs terraform init --backend-config=../../backends/development.tfvars'
alias init-labs-qa='aws-profile -p upscan-labs terraform init --backend-config=../../backends/qa.tfvars'
alias init-labs-staging='aws-profile -p upscan-labs terraform init --backend-config=../../backends/staging.tfvars'
alias select-development-profile='aws-profile -p upscan-labs terraform workspace select development'
alias select-qa-profile='aws-profile -p upscan-labs terraform workspace select qa'
alias select-staging-profile='aws-profile -p upscan-labs terraform workspace select staging'
alias save-plan='aws-profile -p upscan-labs terraform plan -out tfplan.out'
alias show-plan-json='aws-profile -p upscan-labs terraform show -json tfplan.out'
alias update-provider='aws-profile -p upscan-labs  terraform state replace-provider -- -/aws hashicorp/aws'

